### ISSUE TITLE
Cannot connect to the database

### ISSUE THREAD

**Issue by bery** [bitnami/bitnami-docker-ghost#70]
**Description**

If I try to install ghost with default values.yml, the installation fails and user bn_ghost cannot connect to the database. Could you have a look please?

```
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at my-release-mariadb:3306
mysql-c ERROR [canConnect] Connection with 'bn_ghost' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_ghost' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_ghost' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_ghost' user is unsuccessful 
mysql-c ERROR [canConnect] Connection with 'bn_ghost' user is unsuccessful
Error executing 'postInstallation': Cannot connect to MySQL server: 
MySQL command failed to run. Error:  
ERROR 1045 (28000): Access denied for user 'bn_ghost'@'10.20.2.204' (using password: YES) 
```
**Steps to reproduce the issue:**

1. helm install --name my-release stable/ghost

**Describe the results you received:**

Installation fails, connection to the database cannot be established

**Describe the results you expected:**

Successful installation

**Version**

4.0.20

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Google kubernetes engine

**Comment by tompizmor** [comment]
Hi @bery,

I couldn't reproduce the error with the latest chart version:

```
ghosttest	1       	Thu Sep 13 10:40:07 2018	DEPLOYED	ghost-4.0.20	default
```

As you can see in the mariadb logs, the database and user are created:

```
mariadb INFO  ==> Creating database bitnami_ghost...
mariadb INFO  ==> Creating user bn_ghost...
mariadb INFO  ==> Granting access to bn_ghost to the database bitnami_ghost...
mariadb INFO
mariadb INFO  ########################################################################
mariadb INFO   Installation parameters for mariadb:
mariadb INFO     Root User: root
mariadb INFO     Root Password: **********
mariadb INFO     Database: bitnami_ghost
mariadb INFO     Username: bn_ghost
mariadb INFO     Password: **********
mariadb INFO   (Passwords are not shown for security reasons)
mariadb INFO  ########################################################################
```

And in the ghost logs the connection is successful:

```
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at ghosttest-mariadb:3306
mysql-c INFO  MySQL server listening and working at ghosttest-mariadb:3306
```

Which is the exact command that you are running? Was the mariadb pod restarted? Can you check the logs?

**Comment by tompizmor** [comment]
mmm...! 🤔 
Was the ghost container restarted before showing the database error? Maybe the issue is that ghost was restarted the first time because of another reason and the new scheduled pod starts Ghost with a different database password. 

You can try to install the helm chart specifying the Ghost database password to make sure that always uses the same and check if Ghost fails for other reason or start successfully.

`helm install stable/ghost --set mariadb.db.password=YOUR_PASSWORD`

**Comment by bery** [comment]
Nope. Result is still the same. Steps taken, maybe I'm doing something wrong: 

1. kubectl create ns ghost

**Comment by tompizmor** [comment]
Hi @bery,

Following your steps, I could reproduce the issue. The issue is in step 4, where you should also specify the MariaDB password. (We will update the NOTES.txt file). 

So you have to run this command:

```
helm upgrade ghost --set serviceType=LoadBalancer,ghostHost=$APP_HOST,mariadb.db.password=YOUR_PASSWORD stable/ghost
```
In the beginning, I couldn't reproduce because I was specifying the Ghost host in the first install command.

**Comment by tompizmor** [comment]
Glad to help! 🙂
