### ISSUE TITLE
How to force this image to recreate config.production.json?

### ISSUE THREAD

**Issue by acim** [bitnami/bitnami-docker-ghost#93]
I already have running Ghost container in Kubernetes and I want to subsequently set SMTP parameters, but I don't know how to force the container to recreate config.production.json from environment variables?

**Comment by miguelaeh** [comment]
Hi @acim ,
Since your config.production.json will be already persisted the container logic will not create it again when adding new env vars. You need to configure ghost manually either using the UI or editing the file manually.

**Comment by acim** [comment]
Can we move this to feature request in this case? I saw you already have .initialized file and it would make lot of sense if .initialized gets delete to reccreate config.production.json again? If file .initialized is used for some other logic, you may introduce new file like .configured or whatever.
I use this image via Helm chart and it would be really nice if chart gets reconfigured to have some easy way to reconfigure config.production.json as well. Deleting one and killing container would be good enough.

**Comment by miguelaeh** [comment]
Hi @acim ,
This is something that is not possible to be done in non-stateless applications. We are moving all the container logics to use bash to be configured instead of javascript. We will evaluate this and if it is possible for Ghost we will do it on the migration.
By the moment you can use the UI so you don't create a typo into the config file.
Regards

**Comment by acim** [comment]
That would be nice, thank you.
