### ISSUE TITLE
Launch Ghost without creating user account

### ISSUE THREAD

**Issue by iamtk** [bitnami/bitnami-docker-ghost#98]
This is a question, possible feature request, not a bug.

Is it possible to launch Ghost using this Bitnami image without a creating a Ghost user account (username, email, password, blog title)?  This way the user is presented with the attached screens when visiting the Ghost admin URL for the first time.

![Screenshot_2020-12-23 Setup - Ghost](https://user-images.githubusercontent.com/8607394/102998133-7c333c00-451e-11eb-8c6b-97a68c123c39.png)
![Screenshot_2020-12-23 Setup - Ghost(1)](https://user-images.githubusercontent.com/8607394/102998128-7a697880-451e-11eb-8e83-2cc9a8f8dd7f.png)

I've tried not using (or leaving empty) the following variables (-e GHOST_USERNAME="", -e GHOST_EMAIL="", -e GHOST_PASSWORD="",  -e BLOG_TITLE="") but the image just uses the default env variables set in the main dockerfile (i.e. user@example.com, bitnami123).

Thanks.

**Comment by dani8art** [comment]
Hi @iamtk currently it is not possible our configuration logic is initializing the instance always with an admin user, a blog title, etc.

However, it could be interesting to support this feature, it is cool, due to there is a working way to initialize ghost and regarding priorities and internal milestones we can't give you an ETA. Nevertheless, if it is important, you feel you can handle it, and you have a chance to create a PR we would be happy to handle it.

I can give you some tips for managing this:

Ghost configuration is handle by a nami module. You can find the configuration scripts and the nami's files here:

```console
$ ls -la .nami/components/com.bitnami.ghost/
```

The main components of a `nami` module are:

- `.nami/components/com.bitnami.ghost/main.js` and `.nami/components/com.bitnami.ghost/helpers.js`  where the logic is implemented, this is executed at container runtime and will configure the Ghost instance.
- `.nami/components/com.bitnami.ghost/nami.json` where some metadata and properties are stored.
- `/ghost-inputs.json` this file maps the environment variables to `nami` module properties.

So if you want to add a new property you would need to do the following:

- Add a new property to nami.json, e.g. skipUserDataInitialization
- Add logic in `main.js` as if `$app.skipUserDataInitialization` is `false` then skip this kind of logic. There are some utils modules that are preloaded in nami like $file, $os, etc...
- Add a mapping between env vars and `nami` properties in `ghost-inputs.json`

I hope you are finally encouraged to do it.

**Comment by iamtk** [comment]
@dani8art Thank you for the instructions. I'm using the image as it is at present however if I need this in future I will return to your guide.
